//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vodTimeControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class custBudget
    {
        public int custBudgetID { get; set; }
        public int customerID { get; set; }
        public string period { get; set; }
        public Nullable<decimal> monthAmount { get; set; }
        public Nullable<int> monthHours { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
