//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vodTimeControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class timeTrackRow
    {
        public int timeTrackRowID { get; set; }
        public int timeTrackHeadID { get; set; }
        public int subProjectID { get; set; }
        public decimal hours { get; set; }
        public System.DateTime regDate { get; set; }
        public string note { get; set; }
        public Nullable<int> reportPeriodId { get; set; }
    
        public virtual reportPeriod reportPeriod { get; set; }
        public virtual subProject2 subProject2 { get; set; }
        public virtual timeTrackHead timeTrackHead { get; set; }
    }
}
