//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vodTimeControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class timeTrackHead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public timeTrackHead()
        {
            this.timeTrackRow = new HashSet<timeTrackRow>();
        }
    
        public int timeTrackHeadID { get; set; }
        public int customerID { get; set; }
        public System.DateTime tDate { get; set; }
        public string winUserID { get; set; }
        public int userId { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual timeTrackHead timeTrackHead1 { get; set; }
        public virtual timeTrackHead timeTrackHead2 { get; set; }
        public virtual userTbl userTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timeTrackRow> timeTrackRow { get; set; }
    }
}
